### ISSUE TITLE
请问矩形框标注的label会出现重复几个置信度的情况如何解决？

### ISSUE THREAD

**Issue by nuaa-lh** [ncdhz/YoloV5-LibTorch#1]

**Comment by nuaa-lh** [comment]
![1](https://user-images.githubusercontent.com/74602764/131256195-de8b501a-0cdf-4105-b3d5-a78a63a8be4b.png)

**Comment by ncdhz** [comment]
没有看到邮件，请问问题解决了吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ncdhz/YoloV5-LibTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月29日(星期天) 晚上11:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ncdhz/YoloV5-LibTorch] 请问矩形框标注的label会出现重复几个置信度的情况如何解决？ (#1)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
